services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft-forge-1.21.8
    ports:
      - "25565:25565"
      - "25575:25575"
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.21.8"
      MEMORY: "4G"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "changeme"
      ONLINE_MODE: "FALSE"
    volumes:
      - ./minecraft-data:/data
      - ./mods:/data/mods
    stdin_open: true
    tty: true
    restart: always
  playit:
    image: ghcr.io/playit-cloud/playit-agent:0.16
    network_mode: host
    environment:
      - SECRET_KEY=${PLAYIT_SECRET_KEY}
    restart: always
